-- MySQL Script generated by MySQL Workbench
-- Wed Aug 18 13:58:14 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Table `PD`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `PD` (
  `pd_id` INT NOT NULL,
  `pd_code` INT NULL,
  `pd_desc` VARCHAR(75) NULL,
  PRIMARY KEY (`pd_id`),
  UNIQUE INDEX `pd_id_UNIQUE` (`pd_id` ASC) VISIBLE)
ENGINE = MyISAM;


-- -----------------------------------------------------
-- Table `KY`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `KY` (
  `ky_id` INT NOT NULL,
  `ky_code` INT NULL,
  `ky_desc` VARCHAR(75) NULL,
  UNIQUE INDEX `ky_id_UNIQUE` (`ky_id` ASC) VISIBLE,
  PRIMARY KEY (`ky_id`))
ENGINE = MyISAM;


-- -----------------------------------------------------
-- Table `LAW`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `LAW` (
  `law_id` INT NOT NULL,
  `law_code` VARCHAR(45) NULL,
  `category` VARCHAR(2) NULL,
  PRIMARY KEY (`law_id`),
  UNIQUE INDEX `law_id_UNIQUE` (`law_id` ASC) VISIBLE)
ENGINE = MyISAM;


-- -----------------------------------------------------
-- Table `GPS_COORDS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `GPS_COORDS` (
  `GPS_id` INT NOT NULL,
  `longitude` DECIMAL(12,10) NULL,
  `latitude` DECIMAL(12,10) NULL,
  PRIMARY KEY (`GPS_id`),
  UNIQUE INDEX `GPS_id_UNIQUE` (`GPS_id` ASC) VISIBLE)
ENGINE = MyISAM;


-- -----------------------------------------------------
-- Table `MAP_COORDS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `MAP_COORDS` (
  `map_id` INT NOT NULL,
  `x` INT NULL,
  `y` INT NULL,
  PRIMARY KEY (`map_id`),
  UNIQUE INDEX `map_id_UNIQUE` (`map_id` ASC) VISIBLE)
ENGINE = MyISAM;


-- -----------------------------------------------------
-- Table `LOCATION_INFO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `LOCATION_INFO` (
  `LOCATION_INFO_ID` INT NOT NULL,
  `arrest_precinct` INT NULL,
  `boro_name` VARCHAR(45) NULL,
  PRIMARY KEY (`LOCATION_INFO_ID`),
  UNIQUE INDEX `LOCATION_INFO_ID_UNIQUE` (`LOCATION_INFO_ID` ASC) VISIBLE)
ENGINE = MyISAM;


-- -----------------------------------------------------
-- Table `PERPETRATOR_INFO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `PERPETRATOR_INFO` (
  `perp_id` INT NOT NULL,
  `age_group` VARCHAR(45) NULL,
  `sex` VARCHAR(2) NULL,
  `race` VARCHAR(45) NULL,
  PRIMARY KEY (`perp_id`),
  UNIQUE INDEX `perp_id_UNIQUE` (`perp_id` ASC) VISIBLE)
ENGINE = MyISAM;


-- -----------------------------------------------------
-- Table `ARRESTS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ARRESTS` (
  `arrest_id` INT NOT NULL,
  `arrest_date` DATE NULL,
  `jurisdiction` INT NULL,
  `PD_pd_id` INT NOT NULL,
  `KY_ky_id` INT NOT NULL,
  `LAW_law_id` INT NOT NULL,
  `GPS_COORDS_GPS_id` INT NOT NULL,
  `MAP_COORDS_map_id` INT NOT NULL,
  `LOCATION_INFO_LOCATION_INFO_ID` INT NOT NULL,
  `PERPETRATOR_INFO_perp_id` INT NOT NULL,
  PRIMARY KEY (`arrest_id`),
  UNIQUE INDEX `arrest_id_UNIQUE` (`arrest_id` ASC) VISIBLE,
  INDEX `fk_ARRESTS_PD1_idx` (`PD_pd_id` ASC) VISIBLE,
  INDEX `fk_ARRESTS_KY1_idx` (`KY_ky_id` ASC) VISIBLE,
  INDEX `fk_ARRESTS_LAW1_idx` (`LAW_law_id` ASC) VISIBLE,
  INDEX `fk_ARRESTS_GPS_COORDS1_idx` (`GPS_COORDS_GPS_id` ASC) VISIBLE,
  INDEX `fk_ARRESTS_MAP_COORDS1_idx` (`MAP_COORDS_map_id` ASC) VISIBLE,
  INDEX `fk_ARRESTS_LOCATION_INFO1_idx` (`LOCATION_INFO_LOCATION_INFO_ID` ASC) VISIBLE,
  INDEX `fk_ARRESTS_PERPETRATOR_INFO1_idx` (`PERPETRATOR_INFO_perp_id` ASC) VISIBLE)
ENGINE = MyISAM;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
